import { PrometheusClient } from "./prometheus.js";
import type { Observation } from "./types.js";

/**
 * How far back the assessment looks.
 *
 * The observation window is deliberately short. Prometheus already owns
 * "has this been sustained for a while" through alerting `for:` clauses; the
 * decision layer only interprets the current state.
 */
export const OBSERVATION_WINDOW_SECONDS = 60;

/**
 * Traffic generated by the harness is not user traffic. `/work` is the load
 * generator, `/metrics` is scraped every few seconds, and `/health` is the
 * container healthcheck, so all three are excluded from request rate, latency
 * and error rate. In a customer environment the same filtering is done with a
 * per-service route allowlist.
 */
const USER_TRAFFIC = 'route!~"/work|/metrics|/health"';

const window = (offsetSeconds = 0): string =>
  `[${OBSERVATION_WINDOW_SECONDS}s]${offsetSeconds > 0 ? ` offset ${offsetSeconds}s` : ""}`;

const QUERIES = {
  // Fraction of CPU time that is not idle, across every core of the node.
  cpuUtilization: `1 - avg(rate(node_cpu_seconds_total{mode="idle"}${window()}))`,

  p95LatencySeconds: `histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{${USER_TRAFFIC}}${window()})))`,

  requestRate: `sum(rate(http_requests_total{${USER_TRAFFIC}}${window()}))`,

  // The same rate over the window immediately before the observation window,
  // used to tell a traffic increase apart from a traffic collapse.
  previousRequestRate: `sum(rate(http_requests_total{${USER_TRAFFIC}}${window(OBSERVATION_WINDOW_SECONDS)}))`,

  // `sum()` over an empty vector returns an empty result, not 0. Until the
  // service has returned a single 5xx there is no matching series, so without
  // `or vector(0)` the whole error rate disappears and a perfectly healthy
  // service would look like it had no error data at all.
  //
  // The denominator is deliberately left alone: with no requests at all there
  // is genuinely no evidence about user-visible impact, and the decision engine
  // should treat that as unknown rather than as a 0% error rate.
  errorRate: [
    `(sum(rate(http_requests_total{${USER_TRAFFIC},status=~"5.."}${window()})) or vector(0))`,
    "/",
    `sum(rate(http_requests_total{${USER_TRAFFIC}}${window()}))`,
  ].join(" "),
} as const;

export async function collectObservation(
  prometheus: PrometheusClient,
): Promise<Observation> {
  const [cpuUtilization, p95LatencySeconds, errorRate, requestRate, previousRequestRate] =
    await Promise.all([
      prometheus.queryScalar(QUERIES.cpuUtilization),
      prometheus.queryScalar(QUERIES.p95LatencySeconds),
      prometheus.queryScalar(QUERIES.errorRate),
      prometheus.queryScalar(QUERIES.requestRate),
      prometheus.queryScalar(QUERIES.previousRequestRate),
    ]);

  return {
    collectedAt: new Date().toISOString(),
    cpuUtilization,
    p95LatencyMs: p95LatencySeconds === null ? null : p95LatencySeconds * 1000,
    errorRate,
    requestRate,
    previousRequestRate,
    observationWindowSeconds: OBSERVATION_WINDOW_SECONDS,
  };
}
